version: '3'

services:
  docker-mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root123456
      - MYSQL_DATABASE=produto
      - MYSQL_PASSWORD=user123456
    ports:
      - 6604:3306
  produto:
    image: produto
    depends_on:
      - docker-mysql
    ports:
      - 8091:8091
    environment:
      - DATABASE_HOST=docker-mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root123456
      - DATABASE_NAME=produto
      - DATABASE_PORT=3306